### ISSUE TITLE
git问题

### ISSUE THREAD

**Issue by furuchulie** [Ericsii/rm_vision#1]
![IMG_20231201_222157](https://github.com/Ericsii/rm_vision/assets/132684869/819205ba-611f-4a30-921a-79d2313d6688)
git clone 时onnx文件会失败，用git lfs来手动add一下还是不行

**Comment by Ericsii** [comment]
这个问题可以暂时使用沈航开源的onnx模型，或者使用我原仓库这个onnx
https://itlkineticpanda.coding.net/public/23chaoduiitlkineticpanda/rm_vision/git/files/develop/openvino_armor_detector/model/opt-1208-001.onnx

**Comment by Ericsii** [comment]
git lfs文件已经重新上传，本地测试可以直接git clone，问题关闭

**Comment by Ericsii** [comment]
git lfs文件已经重新上传，本地测试可以直接git clone，问题关闭
